            - name: WakaTime Coding Statistics
  # You may pin to the exact commit or the version.
  # uses: tariksahni/coding-stats-wakatime@71e809c34adb51557dcbbb0f5862da04c18f8e2b
  uses: tariksahni/coding-stats-wakatime@v1.0.1
  with:
    # WakaTime API Key
    WAKATIME_API_KEY: waka_ceb4fa10-0d79-4af9-9c51-8c7bf51c6f38
    # Github token of the repo for the authentication
    REPO_TOKEN: 
          
